version: '3.8'

services:
  # Single PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: postgres-foodybuddy-prod
    environment:
      POSTGRES_DB: foodybuddy
      POSTGRES_USER: foodybuddy_user
      POSTGRES_PASSWORD: foodybuddy_password
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init-schemas.sql:/docker-entrypoint-initdb.d/init-schemas.sql
    networks:
      - foodybuddy-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U foodybuddy_user -d foodybuddy"]
      interval: 10s
      timeout: 5s
      retries: 5

  foodybuddy-web:
    build: 
      context: ./foodybuddy-web
      dockerfile: Dockerfile
    image: foodybuddy.prod.web:latest
    container_name: foodybuddy-web-prod
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_BASE_URL=http://localhost:8080
      - PORT=3000
      - HOSTNAME=0.0.0.0
    depends_on:
      - foodybuddy-gateway
    networks:
      - foodybuddy-network
    restart: unless-stopped

  foodybuddy-gateway:
    build: 
      context: ./foodybuddy-gateway
      dockerfile: Dockerfile
    image: foodybuddy.prod.gateway:latest
    container_name: foodybuddy-gateway-prod
    ports:
      - "8080:8080"
    # Profile is set in Dockerfile
    depends_on:
      - postgres
      - foodybuddy-orders
      - foodybuddy-payments
    networks:
      - foodybuddy-network
    restart: unless-stopped

  foodybuddy-orders:
    build: 
      context: ./foodybuddy-orders
      dockerfile: Dockerfile
    image: foodybuddy.prod.orders:latest
    container_name: foodybuddy-orders-prod
    ports:
      - "8081:8081"
    # Profile is set in Dockerfile
    depends_on:
      - postgres
    networks:
      - foodybuddy-network
    restart: unless-stopped

  foodybuddy-payments:
    build: 
      context: ./foodybuddy-payments
      dockerfile: Dockerfile
    image: foodybuddy.prod.payments:latest
    container_name: foodybuddy-payments-prod
    ports:
      - "8082:8082"
    # Profile is set in Dockerfile
    depends_on:
      - postgres
    networks:
      - foodybuddy-network
    restart: unless-stopped

networks:
  foodybuddy-network:
    driver: bridge
    name: foodybuddy-network-prod

volumes:
  postgres-data:
    name: foodybuddy-postgres-single-db-prod