apiVersion: v1
kind: Secret
metadata:
  name: foodybuddy-database-secret
  namespace: foodybuddy
  labels:
    app: foodybuddy
    component: database
    type: credentials
type: Opaque
data:
  # Base64 encoded values
  DB_USERNAME: Zm9vZHlidWRkeV91c2Vy
  DB_PASSWORD: Zm9vZHlidWRkeV9wYXNzd29yZA==
