apiVersion: apps/v1
kind: Deployment
metadata:
  name: foodybuddy-gateway
  namespace: foodybuddy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: foodybuddy-gateway
  template:
    metadata:
      labels:
        app: foodybuddy-gateway
    spec:
      containers:
      - name: foodybuddy-gateway
        image: foodybuddy.prod.gateway:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          protocol: TCP
        env:
        # Spring Configuration
        - name: SPRING_PROFILES_ACTIVE
          valueFrom:
            configMapKeyRef:
              name: foodybuddy-gateway-config
              key: SPRING_PROFILES_ACTIVE
        # Database Configuration
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: foodybuddy-gateway-config
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: foodybuddy-gateway-config
              key: DB_PORT
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: foodybuddy-gateway-config
              key: DB_NAME
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: foodybuddy-gateway-config
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: foodybuddy-gateway-config
              key: DB_PASSWORD
        - name: DB_SCHEMA_GATEWAY
          valueFrom:
            configMapKeyRef:
              name: foodybuddy-gateway-config
              key: DB_SCHEMA_GATEWAY
        # Service URLs Configuration
        - name: ORDERS_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: foodybuddy-gateway-config
              key: ORDERS_SERVICE_URL
        - name: PAYMENTS_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: foodybuddy-gateway-config
              key: PAYMENTS_SERVICE_URL
        - name: WEB_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: foodybuddy-gateway-config
              key: WEB_SERVICE_URL
        - name: ORDERS_SERVICE_CREATE_ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: foodybuddy-gateway-config
              key: ORDERS_SERVICE_CREATE_ENDPOINT
        - name: ORDERS_SERVICE_STATUS_ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: foodybuddy-gateway-config
              key: ORDERS_SERVICE_STATUS_ENDPOINT
        - name: PAYMENTS_SERVICE_PROCESS_ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: foodybuddy-gateway-config
              key: PAYMENTS_SERVICE_PROCESS_ENDPOINT
        - name: PAYMENTS_SERVICE_REFUND_ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: foodybuddy-gateway-config
              key: PAYMENTS_SERVICE_REFUND_ENDPOINT
        # JPA Configuration
        - name: JPA_SHOW_SQL
          valueFrom:
            configMapKeyRef:
              name: foodybuddy-gateway-config
              key: JPA_SHOW_SQL
        - name: JPA_HIBERNATE_DDL_AUTO
          valueFrom:
            configMapKeyRef:
              name: foodybuddy-gateway-config
              key: JPA_HIBERNATE_DDL_AUTO
        # Logging Configuration
        - name: LOG_LEVEL_GATEWAY
          valueFrom:
            configMapKeyRef:
              name: foodybuddy-gateway-config
              key: LOG_LEVEL_GATEWAY
        - name: LOG_PATTERN_CONSOLE
          valueFrom:
            configMapKeyRef:
              name: foodybuddy-gateway-config
              key: LOG_PATTERN_CONSOLE
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 90
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 15
          timeoutSeconds: 5
          failureThreshold: 3
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
      restartPolicy: Always
