apiVersion: apps/v1
kind: Deployment
metadata:
  name: foodybuddy-orders
  namespace: foodybuddy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: foodybuddy-orders
  template:
    metadata:
      labels:
        app: foodybuddy-orders
    spec:
      containers:
      - name: foodybuddy-orders
        image: foodybuddy.prod.orders:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8081
          protocol: TCP
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "prod"
        # Database Configuration
        - name: DB_HOST
          value: "postgres-db-service"
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          value: "foodybuddy"
        - name: DB_USERNAME
          value: "foodybuddy_user"
        - name: DB_PASSWORD
          value: "foodybuddy_password"
        - name: DB_SCHEMA_ORDERS
          value: "orders"
        # Service URLs Configuration
        - name: GATEWAY_URL
          value: "http://foodybuddy-gateway:8080"
        # JPA Configuration
        - name: JPA_SHOW_SQL
          value: "false"
        - name: JPA_HIBERNATE_DDL_AUTO
          value: "validate"
        - name: JPA_FORMAT_SQL
          value: "false"
        # Logging Configuration
        - name: LOG_LEVEL_ORDERS
          value: "INFO"
        - name: LOG_PATTERN_CONSOLE
          value: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8081
          initialDelaySeconds: 90
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8081
          initialDelaySeconds: 60
          periodSeconds: 15
          timeoutSeconds: 5
          failureThreshold: 3
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
      restartPolicy: Always
