apiVersion: apps/v1
kind: Deployment
metadata:
  name: foodybuddy-orders
  namespace: foodybuddy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: foodybuddy-orders
  template:
    metadata:
      labels:
        app: foodybuddy-orders
    spec:
      containers:
      - name: foodybuddy-orders
        image: foodybuddy.prod.orders:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8081
          protocol: TCP
        env:
        # Spring Configuration
        - name: SPRING_PROFILES_ACTIVE
          valueFrom:
            configMapKeyRef:
              name: foodybuddy-orders-config
              key: SPRING_PROFILES_ACTIVE
        # Database Configuration
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: foodybuddy-orders-config
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: foodybuddy-orders-config
              key: DB_PORT
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: foodybuddy-orders-config
              key: DB_NAME
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: foodybuddy-orders-config
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: foodybuddy-orders-config
              key: DB_PASSWORD
        - name: DB_SCHEMA_ORDERS
          valueFrom:
            configMapKeyRef:
              name: foodybuddy-orders-config
              key: DB_SCHEMA_ORDERS
        # Service URLs Configuration
        - name: GATEWAY_URL
          valueFrom:
            configMapKeyRef:
              name: foodybuddy-orders-config
              key: GATEWAY_URL
        # JPA Configuration
        - name: JPA_SHOW_SQL
          valueFrom:
            configMapKeyRef:
              name: foodybuddy-orders-config
              key: JPA_SHOW_SQL
        - name: JPA_HIBERNATE_DDL_AUTO
          valueFrom:
            configMapKeyRef:
              name: foodybuddy-orders-config
              key: JPA_HIBERNATE_DDL_AUTO
        - name: JPA_FORMAT_SQL
          valueFrom:
            configMapKeyRef:
              name: foodybuddy-orders-config
              key: JPA_FORMAT_SQL
        # Logging Configuration
        - name: LOG_LEVEL_ORDERS
          valueFrom:
            configMapKeyRef:
              name: foodybuddy-orders-config
              key: LOG_LEVEL_ORDERS
        - name: LOG_PATTERN_CONSOLE
          valueFrom:
            configMapKeyRef:
              name: foodybuddy-orders-config
              key: LOG_PATTERN_CONSOLE
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8081
          initialDelaySeconds: 90
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8081
          initialDelaySeconds: 60
          periodSeconds: 15
          timeoutSeconds: 5
          failureThreshold: 3
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
      restartPolicy: Always
