apiVersion: apps/v1
kind: Deployment
metadata:
  name: foodybuddy-web
  namespace: foodybuddy
spec:
  replicas: 4
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: foodybuddy-web
  template:
    metadata:
      labels:
        app: foodybuddy-web
    spec:
      containers:
      - name: foodybuddy-web
        image: foodybuddy.prod.web:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
          protocol: TCP
        env:
        # Node.js Configuration
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: foodybuddy-web-config
              key: NODE_ENV
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: foodybuddy-web-config
              key: PORT
        - name: HOSTNAME
          valueFrom:
            configMapKeyRef:
              name: foodybuddy-web-config
              key: HOSTNAME
        # API Configuration
        - name: NEXT_PUBLIC_API_BASE_URL
          valueFrom:
            configMapKeyRef:
              name: foodybuddy-web-config
              key: NEXT_PUBLIC_API_BASE_URL
        - name: GATEWAY_BASE_URL
          valueFrom:
            configMapKeyRef:
              name: foodybuddy-web-config
              key: GATEWAY_BASE_URL
        # Logging Configuration
        - name: NEXT_LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: foodybuddy-web-config
              key: NEXT_LOG_LEVEL
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 15
          timeoutSeconds: 5
          failureThreshold: 3
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
      restartPolicy: Always